name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby 3.4.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.4

      - name: Install Bundler 2.6.9
        run: gem install bundler -v 2.6.9

      - name: Bundle install
        run: bundle install --jobs 4 --retry 3

      - name: Run tests
        run: bundle exec rake test

      - name: Run Rubocop
        run: bundle exec rubocop
